### ISSUE TITLE
Pass options object to control

### ISSUE THREAD

**Issue by mikecasas** [ziad-saab/react-checkbox-group#19]
Is there a way to pass an options object to the control, and have the checkbox mapping done automatically? I was able to build my check boxes like the example in #12, but I was wondering if I could reduce the few lines of boilerplate.

**Comment by ziad-saab** [comment]
@mikecasas you can get the result you want with a wrapper component. It seems to be the way to go these days. Something like this:

```javascript
var MyCheckboxGroup = React.createClass({
  render: function() {
    var {options, ...rest} = this.props;
    return <CheckboxGroup ...rest>{options.map(...)}</CheckboxGroup>;
  }
})
```

What do you think?

**Comment by mikecasas** [comment]
@ziad-saab I would prefer to have the map extracted away into the component, but I understand the wrapper component.

Thanks for your help!

**Comment by ziad-saab** [comment]
@mikecasas my reasoning behind this is that there will be a mapping to do either way. Here's what I mean:

Let's say that the `CheckboxGroup` component accepts an `options` prop that looks like this:

```json
[
  {"label": "Watermelon", value: "watermelon"},
  {"label": "Pineapple", value: "pineapple"},
  ...
]
```

If your data doesn't look 100% like this, then you'll need to map your data to this specific format, which the component would then map to the checkboxes.

Rather than doing that, might as well just do the mapping from your data to the `<Checkbox>`es themselves. What do you think?

**Comment by mikecasas** [comment]
I guess I am used to using libraries where you conform your data to their spec. That is the trade off to use someone else's work. So yes, I am assuming I would have to pass an array looking exactly like the one you described in order to get the benefits of a default mapping. Otherwise I would need to build my checkbox items through my own custom map function.

It's six of one, and half a dozen of another. I know in the end that I as a component consumer have to do some work. Either conform my data or handle the mapping on my own. I personally prefer first method, but that's just me.
